[versions]
androidxConstraintlayout = "2.2.0"
comAndroid = "8.7.3"
orgJetbrainsKotlinAndroid = "1.9.24"
orgJlleitschuhGradleKtlint = "12.1.1"
comGoogleAndroidMaterial = "1.12.0"
comInnovatricsDot = "8.6.1"

[libraries]
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
com-google-android-material = { group = "com.google.android.material", name = "material", version.ref = "comGoogleAndroidMaterial" }
com-innovatrics-dot-document = { group = "com.innovatrics.dot", name = "dot-document", version.ref = "comInnovatricsDot" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "comAndroid" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "orgJetbrainsKotlinAndroid" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "orgJlleitschuhGradleKtlint" }
